// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DataBaseApprochContext))]
    [Migration("20250205111926_CLass_CHange")]
    partial class CLass_CHange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 5, 16, 49, 25, 783, DateTimeKind.Local).AddTicks(2842),
                            Description = "High-end laptop",
                            Name = "Laptop",
                            Price = 1200.50m,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2025, 2, 5, 16, 49, 25, 784, DateTimeKind.Local).AddTicks(4212)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 5, 16, 49, 25, 784, DateTimeKind.Local).AddTicks(4506),
                            Description = "Latest model",
                            Name = "Smartphone",
                            Price = 800.99m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2025, 2, 5, 16, 49, 25, 784, DateTimeKind.Local).AddTicks(4508)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 5, 16, 49, 25, 784, DateTimeKind.Local).AddTicks(4510),
                            Description = "Noise-cancelling",
                            Name = "Headphones",
                            Price = 150.75m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2025, 2, 5, 16, 49, 25, 784, DateTimeKind.Local).AddTicks(4511)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
